company = set(("Google", "ShowMeAI", "Taobao"))
print(id(company))
company.add("SoftBank")
print(company)
print(id(company))
company.update({"Taobao","CSDN","ByteDance"})
print(company)
print(id(company))